# fly.toml app configuration file generated for personalizados-web-summer-breeze-8754 on 2024-11-10T01:02:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personalizados-web-summer-breeze-8754'
primary_region = 'mia'

[build]
  dockerfile = './DockerFile'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
