name: Deploy Vite Build to Hostinger (Dev)

on:
  push:
    branches: [dev] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar dependencias y build de Vite
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 3️⃣ Subir build al dominio de prueba y limpiar carpeta
      - name: Deploy dist via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST_DEV }}
          username: ${{ secrets.FTP_USER_DEV }}
          password: ${{ secrets.FTP_PASS_DEV }}
          local-dir: ./dist/               
          server-dir: /public_html/
          dangerous-clean-slate: true       # Borra archivos antiguos
