name: Deploy Vite Build to Hostinger

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar dependencias y crear build de Vite
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 3️⃣ Subir build al FTP y limpiar carpeta remota
      - name: Deploy dist via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./dist/                # Carpeta generada por Vite
          server-dir: /personalizadosrd/
          dangerous-clean-slate: true       # Borra archivos antiguos
